apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-volume
  labels:
    app: web
spec:
  volumes:
    - name: web-volume
      persistentVolumeClaim:
        claimName: nginx-pvc
  containers:
  - name: nginx
    image: nginx:stable-alpine
    ports:
      - containerPort: 80
    resources:
      limits:
        cpu: 500m
        memory: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
spec: